# Generated by Django 5.2.5 on 2025-09-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year')], null=True),
        ),
    ]
