# Generated by Django 5.2.5 on 2025-09-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[("B.Sc.'C.S.'", 'B.Sc.Computer Science'), ('B.C.A', 'B.Computer Application'), ('B.Com', 'B. Commerce')], default='B.Com', max_length=20),
        ),
    ]
