# Generated by Django 5.2.5 on 2025-09-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_borrowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='handover_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
