# Generated by Django 5.2.5 on 2025-09-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_borrowedbook_handover_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Python', 'Python Programming'), ('Java', 'Java Programming'), ('Integration', 'Integral Calculus'), ('Banking', 'Intro to Banking')], max_length=30)),
                ('semester', models.CharField(choices=[('sem1', 'Semester1'), ('sem2', 'Semester2'), ('sem3', 'Semester3'), ('sem4', 'Semester4'), ('sem5', 'Semester5'), ('sem6', 'Semester6')], max_length=10)),
                ('department', models.CharField(choices=[("B.Sc.'C.S.'", 'B.Sc.Computer Science'), ('B.C.A', 'B.Computer Application'), ('B.Com', 'B. Commerce')], max_length=20)),
                ('pdf', models.FileField(upload_to='qns/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
