# Generated by Django 5.2.5 on 2025-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_alter_questionpaper_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='department',
            field=models.CharField(choices=[('B.Sc.C.S.', 'B.Sc.Computer Science'), ('B.C.A.', 'B.Computer Application'), ('B.Com.', 'B.Commerce')], max_length=20),
        ),
    ]
